version: '3'
services:
  node:
    container_name: reflect_bookmarks
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5001
    volumes:
      - ./:/code
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - node-webapp-network
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - node-webapp-network
volumes:
 mongodb:
networks:
  node-webapp-network:
    driver: bridge